### ISSUE TITLE
Can't compile backend application

### ISSUE THREAD

**Issue by lorenzonet** [shindesharad71/Anstagram#51]
`>npx nx serve backend

C:\Lorenzo\MyTest\Anstagram\node_modules\yargs-parser\index.js:802
  var result = parse(args.slice(), opts)
                          ^

TypeError: Cannot read property 'slice' of undefined
    at Parser (C:\Lorenzo\MyTest\Anstagram\node_modules\yargs-parser\index.js:802:27)
    at Object.splitArgsIntoNxArgsAndOverrides (C:\Lorenzo\MyTest\Anstagram\node_modules\@nrwl\workspace\src\command-line\utils.js:43:23)
    at Object.runOne (C:\Lorenzo\MyTest\Anstagram\node_modules\@nrwl\workspace\src\command-line\run-one.js:11:43)
    at Object.initLocal (C:\Lorenzo\MyTest\Anstagram\node_modules\@nrwl\cli\lib\init-local.js:27:65)
    at Object.<anonymous> (C:\Lorenzo\MyTest\Anstagram\node_modules\@nrwl\cli\bin\nx.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
`
any idea how to solve this issue?

**Comment by edu1525** [comment]
Same issue here, can anybody help?

**Comment by shindesharad71** [comment]
It seems to be dependency issue. I will suggest try upgrading project dependencies.

I will try to fix tomorrow. But anyone else able to fix it before please raise PR.

**Comment by lorenzonet** [comment]
After downloaded the latest project code I've tried to update project dependencies, this is the result:

> npm update

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-instagram@0.0.1
npm ERR! Found: @angular/core@10.2.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.0.9" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^11.0.0" from @fortawesome/angular-fontawesome@0.8.2
npm ERR! node_modules/@fortawesome/angular-fontawesome
npm ERR!   @fortawesome/angular-fontawesome@"^0.8.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\loren\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\loren\AppData\Local\npm-cache\_logs\2021-08-30T10_22_06_975Z-debug.log

**Comment by shindesharad71** [comment]
@lorenzonet No need to do `npm update` just install dependencies with `npm i`
